### ISSUE TITLE
Invalid styles in the generated CSS

### ISSUE THREAD

**Issue by valerymelou** [papercss/papercss#73]
I've noticed this rules in the generated CSS. The pseudo class `hover` is applied twice on the same selector.
```
.paper-btn:hover:hover,
button:hover:hover,
input[type=button]:hover:hover {
  -webkit-box-shadow: 2px 8px 4px -6px rgba(0,0,0,.3);
  -moz-box-shadow: 2px 8px 4px -6px rgba(0,0,0,.3);
  box-shadow: 2px 8px 4px -6px rgba(0,0,0,.3)
}
```

I think this is caused by this rule in the `button.less` file:
```
button, .paper-btn, input[type="button"] {
    &:hover{
        .shadow-hover;
    }
}
```

and how the class `.shadow-hover` is styled in `shadows.less`.

I'm not a LESS expert but I think that there is a problem with the way styles defined for `.shadow-hover` are extended to `button:hover`.

**Comment by rhyneav** [comment]
Hmm, this may have been fixed in the develop branch. Have you checked in there yet?

**Comment by valerymelou** [comment]
Just did. It's still there.

**Comment by afzalsayed96** [comment]
I've checked that this issue is still existing in develop as well as master branch. However, I don't really understand what are the side-effects caused by it. What is the solution proposed here?

**Comment by rhyneav** [comment]
I think `.shadow-hover` needs to be moved outside of the `&:hover`.  since `.shadow-hover` includes :hover

**Comment by rhyneav** [comment]
Looks like this has been resolved in 1.4. New code now reads as

```css
.paper-btn:hover,
[type=button]:hover,
button:hover {
  box-shadow: 2px 8px 8px -5px rgba(0,0,0,.3);
  -webkit-transform: translate(0,2px);
  -ms-transform: translate(0,2px);
  transform: translate(0,2px)
}
```
